[redis]
    [redis.common]#接口使用
        Hosts=["172.18.1.4:6379"]
        Type = false #集群模式 或者 单机模式
        Database = 1 #数据库序号
        Password = "" #密码
        PoolSize = 10
        KeyPrefix = ""
        # 关闭指标采集
        DisableMetric = false
        # 关闭链路追踪
	    DisableTrace = false

[[proxyredis]]
Name = "redis"
Node = ["redis.common"]