[cookie]
    #每一个应用独有标识
    appKey = "xmt"
    #过期时间
    expires=180000
    #路径
    path="/"
    #域名
    domain=""
    #https才启用
    secure=false
    #HttpOnly属性
    httpOnly=true
    #hashKey
    hashKey="cookies_hashKey"
    #blockKey
    blockKey="cookies_blockKey" 