[elasticsearch]
    [elasticsearch.common] #接口使用
        # httpClient = true
        URL = ["http://elasticsearch:9200"]
        Username = "elastic"
        Password = "f_ys=SRZQ6wA11b_hf84"
        # scheme = "http"   
        # snifferEnabled = true
        # snifferTimeoutStartup = 10
        # snifferTimeout = 10
        # snifferInterval = 10
        # healthcheckEnabled = true
        # healthcheckTimeoutStartup = 120
        # healthcheckInterval = 10
        # maxRetries = 3
        # gzipEnabled = true
        # errorlog = true
        # tracelog = true
        # 关闭指标采集
        DisableMetric = false
        # 关闭链路追踪
        DisableTrace = false
[[proxyelasticsearch]]
Name = "elasticsearch"
Node = ["elasticsearch.common"]