[mongodb]
    [mongodb.common]
        URI="mongodb://root:654321@172.18.1.2:27017/xmt?authSource=admin&authMechanism=SCRAM-SHA-256"
        MaxConnIdleTime = 1
        MaxPoolSize = 64
        MinPoolSize = 10
        # 关闭指标采集
        DisableMetric = false
        # 关闭链路追踪
	    DisableTrace = false

[[proxymongodb]]
Name = "mongodb"
Node = ["mongodb.common"]