// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: love/love.proto

package love

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request 请求
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

// Reset ...
func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_love_love_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

// String ...
func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage ...
func (*Request) ProtoMessage() {}

// ProtoReflect ...
func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_love_love_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Descriptor Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_love_love_proto_rawDescGZIP(), []int{0}
}

// GetName ...
func (x *Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Response 响应
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

// Reset ...
func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_love_love_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

// String ...
func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

// ProtoMessage ...
func (*Response) ProtoMessage() {}

// ProtoReflect ...
func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_love_love_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Descriptor Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_love_love_proto_rawDescGZIP(), []int{1}
}

// GetResult ...
func (x *Response) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// File_love_love_proto ...
var File_love_love_proto protoreflect.FileDescriptor

var file_love_love_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x6f, 0x76, 0x65, 0x2f, 0x6c, 0x6f, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6c, 0x6f, 0x76, 0x65, 0x22, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x35, 0x0a, 0x04, 0x4c, 0x6f,
	0x76, 0x65, 0x12, 0x2d, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x0d, 0x2e, 0x6c, 0x6f, 0x76, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0e, 0x2e, 0x6c, 0x6f, 0x76, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x6c, 0x6f, 0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_love_love_proto_rawDescOnce sync.Once
	file_love_love_proto_rawDescData = file_love_love_proto_rawDesc
)

func file_love_love_proto_rawDescGZIP() []byte {
	file_love_love_proto_rawDescOnce.Do(func() {
		file_love_love_proto_rawDescData = protoimpl.X.CompressGZIP(file_love_love_proto_rawDescData)
	})
	return file_love_love_proto_rawDescData
}

var file_love_love_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_love_love_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: love.Request
	(*Response)(nil), // 1: love.Response
}
var file_love_love_proto_depIdxs = []int32{
	0, // 0: love.Love.Confession:input_type -> love.Request
	1, // 1: love.Love.Confession:output_type -> love.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_love_love_proto_init() }
func file_love_love_proto_init() {
	if File_love_love_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_love_love_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_love_love_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_love_love_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_love_love_proto_goTypes,
		DependencyIndexes: file_love_love_proto_depIdxs,
		MessageInfos:      file_love_love_proto_msgTypes,
	}.Build()
	File_love_love_proto = out.File
	file_love_love_proto_rawDesc = nil
	file_love_love_proto_goTypes = nil
	file_love_love_proto_depIdxs = nil
}
